default_platform(:android)

platform :android do
  desc "Deploy to internal testing track"
  lane :beta do
    gradle(
      task: "bundle",
      build_type: "Release"
    )
    upload_to_play_store(
      track: "internal",
      json_key: "fastlane/google-play-key.json",
      package_name: "com.aiappbuilder.apptsxmobilebuild1748737300564lw2hm621l"
    )
  end
end